// Part of eYssen. See LICENSE file for full copyright and licensing details.

import { describe, it, expect, beforeEach, vi } from 'vitest'
import { createMemoryDb } from '../../helpers/test-db'
import { createClientWikiTables } from '../../../src/modules/client-wiki/schema.js'
import { createClientWikiService } from '../../../src/modules/client-wiki/wiki-service.js'
import { createWikiAutoUpdate } from '../../../src/modules/client-wiki/auto-update.js'
import { ticketSlug, decisionSlug } from '../../../src/modules/client-wiki/wiki-paths.js'
import { MEMORY_DEFAULT_PROJECT_ID } from '../../../src/modules/memory/types.js'

const PROJECT_A = 'proj-alpha'
const PROJECT_B = 'proj-bravo'
const TICKET_ID = 'conv-alpha-1'
const SESSION_ID = 'sess-bravo-9'

describe('wiki auto-update', () => {
  let wiki: ReturnType<typeof createClientWikiService>
  let conversations: Map<string, {
    id: string
    title: string | null
    projectId: string | null
    messages: Array<{ role: string; content: string }>
  }>
  let stages: Map<string, { id: string; isClosed: boolean }>
  let agent: ReturnType<typeof createWikiAutoUpdate>

  beforeEach(() => {
    const db = createMemoryDb()
    createClientWikiTables(db)
    wiki = createClientWikiService(db)
    conversations = new Map()
    stages = new Map()
    agent = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
    })
  })

  function addTicket(opts: {
    id?: string
    projectId: string | null
    title?: string
    body?: string
  }) {
    const id = opts.id ?? TICKET_ID
    conversations.set(id, {
      id,
      title: opts.title ?? 'Fix the alpha login',
      projectId: opts.projectId,
      messages: [
        { role: 'user', content: opts.body ?? 'Login fails on alpha.' },
        { role: 'assistant', content: 'Reproduced. Patch in review.' },
      ],
    })
    return id
  }

  const ticketsOn = (body: 'title' | 'latest' | 'transcript' = 'transcript') => createWikiAutoUpdate({
    wiki,
    conversations: { get: (id) => conversations.get(id) ?? null },
    stages: { get: (id) => stages.get(id) ?? null },
    projects: { get: () => ({ wikiAutoTickets: true, wikiAutoDecisions: false, wikiTicketBody: body }) },
  })
  const decisionsOn = () => createWikiAutoUpdate({
    wiki,
    conversations: { get: (id) => conversations.get(id) ?? null },
    stages: { get: (id) => stages.get(id) ?? null },
    projects: { get: () => ({ wikiAutoTickets: false, wikiAutoDecisions: true, wikiTicketBody: 'title' }) },
  })

  it('writes a project-scoped ticket page when a card enters a closed stage', () => {
    addTicket({ projectId: PROJECT_A })
    stages.set('done', { id: 'done', isClosed: true })

    const result = ticketsOn().handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })

    expect(result.wrote).toBe(true)
    const page = wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))
    expect(page).not.toBeNull()
    expect(page!.autoGenerated).toBe(true)
    expect(page!.title).toBe('Fix the alpha login')
    expect(page!.contentMd).toContain('Login fails on alpha.')
    expect(page!.slug).toBe('ticket-conv-alpha-1')
    expect(wiki.listPages(PROJECT_B)).toEqual([])
  })

  it('does not write when the stage is still open', () => {
    addTicket({ projectId: PROJECT_A })
    stages.set('doing', { id: 'doing', isClosed: false })

    const result = agent.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'doing' })

    expect(result.wrote).toBe(false)
    expect(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))).toBeNull()
  })

  it('skips the seed catch-all project', () => {
    addTicket({ projectId: MEMORY_DEFAULT_PROJECT_ID })
    stages.set('done', { id: 'done', isClosed: true })

    const result = agent.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })

    expect(result.wrote).toBe(false)
    expect(wiki.listPages(MEMORY_DEFAULT_PROJECT_ID)).toEqual([])
  })

  it('updates an auto-generated ticket page on a later close', () => {
    addTicket({ projectId: PROJECT_A, body: 'First body' })
    stages.set('done', { id: 'done', isClosed: true })
    const opted = ticketsOn()
    opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })

    conversations.set(TICKET_ID, {
      ...conversations.get(TICKET_ID)!,
      messages: [{ role: 'user', content: 'Updated body' }],
    })
    const result = opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })

    expect(result.wrote).toBe(true)
    expect(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.contentMd).toContain('Updated body')
    expect(wiki.getHistory(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.id).length).toBeGreaterThan(1)
  })

  it('does not overwrite a page a human has taken over', () => {
    addTicket({ projectId: PROJECT_A })
    stages.set('done', { id: 'done', isClosed: true })
    const opted = ticketsOn()
    opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    const page = wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!
    wiki.updatePage(page.id, { contentMd: 'Human rewrite', autoGenerated: false }, 'alice', 'edited')

    conversations.set(TICKET_ID, {
      ...conversations.get(TICKET_ID)!,
      messages: [{ role: 'user', content: 'Should not land' }],
    })
    const result = opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })

    expect(result.wrote).toBe(false)
    expect(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.contentMd).toBe('Human rewrite')
    expect(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.autoGenerated).toBe(false)
  })

  it('writes a decision page on the project and does not promote to the vault', () => {
    const vaultPromote = vi.fn()
    const dest = decisionsOn().promoteTeamSession({
      projectId: PROJECT_A,
      session: {
        id: SESSION_ID,
        parentConversationId: TICKET_ID,
        createdAt: '2026-08-30T00:00:00.000Z',
        completedAt: '2026-08-30T01:00:00.000Z',
      },
      entries: [
        { category: 'decision', key: 'auth', value: 'Use session cookies', authorAgentId: 'agent-1' },
        { category: 'finding', key: 'bug', value: 'Null on empty token', authorAgentId: 'agent-2' },
        { category: 'question', key: 'skip', value: 'not durable', authorAgentId: null },
      ],
      vaultPromote,
    })

    expect(dest).toBe('wiki')
    expect(vaultPromote).not.toHaveBeenCalled()
    const page = wiki.getPage(PROJECT_A, decisionSlug(SESSION_ID))
    expect(page).not.toBeNull()
    expect(page!.autoGenerated).toBe(true)
    expect(page!.contentMd).toContain('Use session cookies')
    expect(page!.contentMd).toContain('Null on empty token')
    expect(page!.contentMd).not.toContain('not durable')
    expect(wiki.listPages(PROJECT_B)).toEqual([])
  })

  it('falls back to vault when there is no project to scope a wiki page', () => {
    const vaultPromote = vi.fn(() => ({ path: 'projects/team-sessions/x.md' }))
    const dest = agent.promoteTeamSession({
      projectId: null,
      session: {
        id: SESSION_ID,
        parentConversationId: TICKET_ID,
        createdAt: '2026-08-30T00:00:00.000Z',
        completedAt: '2026-08-30T01:00:00.000Z',
      },
      entries: [
        { category: 'decision', key: 'auth', value: 'Use session cookies', authorAgentId: 'agent-1' },
      ],
      vaultPromote,
    })

    expect(dest).toBe('vault')
    expect(vaultPromote).toHaveBeenCalledOnce()
    expect(wiki.listPages(PROJECT_A)).toEqual([])
  })

  it('does not copy vault project notes onto the wiki', () => {
    const vaultRead = vi.fn()
    const isolated = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
      vault: { read: vaultRead },
    })
    addTicket({ projectId: PROJECT_A })
    stages.set('done', { id: 'done', isClosed: true })
    isolated.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    expect(vaultRead).not.toHaveBeenCalled()
  })

  it('does not write a ticket page unless the project opted tickets in', () => {
    addTicket({ projectId: PROJECT_A })
    stages.set('done', { id: 'done', isClosed: true })
    const result = agent.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    expect(result.wrote).toBe(false)
    expect(wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))).toBeNull()
  })

  it('writes a ticket page when the project enabled tickets, with title-only body by default', () => {
    addTicket({ projectId: PROJECT_A })
    stages.set('done', { id: 'done', isClosed: true })
    const opted = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
      projects: {
        get: (id) => id === PROJECT_A
          ? { wikiAutoTickets: true, wikiAutoDecisions: false, wikiTicketBody: 'title' }
          : null,
      },
    })
    const result = opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    expect(result.wrote).toBe(true)
    const page = wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!
    expect(page.contentMd).toContain('Fix the alpha login')
    expect(page.contentMd).toContain(TICKET_ID)
    expect(page.contentMd).not.toContain('Login fails on alpha.')
    expect(page.contentMd).not.toContain('Reproduced.')
  })

  it('latest body keeps only the last user and assistant turns', () => {
    addTicket({ projectId: PROJECT_A })
    conversations.set(TICKET_ID, {
      ...conversations.get(TICKET_ID)!,
      messages: [
        { role: 'user', content: 'Old question' },
        { role: 'assistant', content: 'Old answer' },
        { role: 'user', content: 'Login fails on alpha.' },
        { role: 'assistant', content: 'Reproduced. Patch in review.' },
      ],
    })
    stages.set('done', { id: 'done', isClosed: true })
    const opted = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
      projects: {
        get: () => ({ wikiAutoTickets: true, wikiAutoDecisions: false, wikiTicketBody: 'latest' }),
      },
    })
    opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    const md = wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.contentMd
    expect(md).toContain('Login fails on alpha.')
    expect(md).toContain('Reproduced. Patch in review.')
    expect(md).not.toContain('Old question')
    expect(md).not.toContain('Old answer')
  })

  it('transcript body keeps the full conversation', () => {
    addTicket({ projectId: PROJECT_A })
    conversations.set(TICKET_ID, {
      ...conversations.get(TICKET_ID)!,
      messages: [
        { role: 'user', content: 'Old question' },
        { role: 'assistant', content: 'Old answer' },
        { role: 'user', content: 'Login fails on alpha.' },
      ],
    })
    stages.set('done', { id: 'done', isClosed: true })
    const opted = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
      projects: {
        get: () => ({ wikiAutoTickets: true, wikiAutoDecisions: false, wikiTicketBody: 'transcript' }),
      },
    })
    opted.handleStageChanged({ conversationId: TICKET_ID, toStageId: 'done' })
    const md = wiki.getPage(PROJECT_A, ticketSlug(TICKET_ID))!.contentMd
    expect(md).toContain('Old question')
    expect(md).toContain('Login fails on alpha.')
  })

  it('does not write a decision page unless the project opted decisions in — vault instead', () => {
    const vaultPromote = vi.fn(() => ({ path: 'projects/team-sessions/x.md' }))
    const dest = agent.promoteTeamSession({
      projectId: PROJECT_A,
      session: {
        id: SESSION_ID,
        parentConversationId: TICKET_ID,
        createdAt: '2026-08-30T00:00:00.000Z',
        completedAt: '2026-08-30T01:00:00.000Z',
      },
      entries: [
        { category: 'decision', key: 'auth', value: 'Use session cookies', authorAgentId: 'agent-1' },
      ],
      vaultPromote,
    })
    expect(dest).toBe('vault')
    expect(vaultPromote).toHaveBeenCalledOnce()
    expect(wiki.getPage(PROJECT_A, decisionSlug(SESSION_ID))).toBeNull()
  })

  it('writes a decision page when the project enabled decisions', () => {
    const vaultPromote = vi.fn()
    const opted = createWikiAutoUpdate({
      wiki,
      conversations: { get: (id) => conversations.get(id) ?? null },
      stages: { get: (id) => stages.get(id) ?? null },
      projects: {
        get: () => ({ wikiAutoTickets: false, wikiAutoDecisions: true, wikiTicketBody: 'title' }),
      },
    })
    const dest = opted.promoteTeamSession({
      projectId: PROJECT_A,
      session: {
        id: SESSION_ID,
        parentConversationId: TICKET_ID,
        createdAt: '2026-08-30T00:00:00.000Z',
        completedAt: '2026-08-30T01:00:00.000Z',
      },
      entries: [
        { category: 'decision', key: 'auth', value: 'Use session cookies', authorAgentId: 'agent-1' },
      ],
      vaultPromote,
    })
    expect(dest).toBe('wiki')
    expect(vaultPromote).not.toHaveBeenCalled()
    expect(wiki.getPage(PROJECT_A, decisionSlug(SESSION_ID))!.contentMd).toContain('Use session cookies')
  })
})
