// Part of eYssen. See LICENSE file for full copyright and licensing details.

import { describe, it, expect, beforeEach } from 'vitest'
import { createMemoryDb } from '../../helpers/test-db'
import { createClientWikiTables } from '../../../src/modules/client-wiki/schema.js'
import { createClientWikiService, UniqueSlugError } from '../../../src/modules/client-wiki/wiki-service.js'
import { renderMarkdown, summarize, escapeHtml } from '../../../src/modules/client-wiki/markdown-render.js'

describe('ClientWikiService', () => {
  let db: ReturnType<typeof createMemoryDb>
  let service: ReturnType<typeof createClientWikiService>

  beforeEach(() => {
    db = createMemoryDb()
    createClientWikiTables(db)
    service = createClientWikiService(db)
  })

  describe('createPage', () => {
    it('creates a page with auto-slug, auto-summary and initial revision', () => {
      const page = service.createPage({
        clientId: 'acme',
        title: 'Architecture Overview',
        contentMd: 'The acme system consists of three services.\n\nMore detail follows.',
        author: 'alice',
      })
      expect(page.id).toBeTruthy()
      expect(page.clientId).toBe('acme')
      expect(page.slug).toBe('architecture-overview')
      expect(page.title).toBe('Architecture Overview')
      expect(page.summary).toContain('acme system consists of three services')
      expect(page.tags).toEqual([])
      expect(page.autoGenerated).toBe(false)
      expect(page.updatedBy).toBe('alice')

      const history = service.getHistory(page.id)
      expect(history).toHaveLength(1)
      expect(history[0].changeSummary).toBe('initial')
    })

    it('respects an explicit slug and normalizes it', () => {
      const page = service.createPage({
        clientId: 'acme', title: 'Overview', slug: 'Custom Slug!!', contentMd: 'x',
      })
      expect(page.slug).toBe('custom-slug')
    })

    it('enforces UNIQUE(clientId, slug)', () => {
      service.createPage({ clientId: 'acme', title: 'Overview', contentMd: 'x' })
      expect(() => service.createPage({ clientId: 'acme', title: 'Overview', contentMd: 'y' }))
        .toThrow(UniqueSlugError)
    })

    it('allows the same slug across different clients', () => {
      const a = service.createPage({ clientId: 'acme', title: 'Overview', contentMd: 'x' })
      const b = service.createPage({ clientId: 'beta', title: 'Overview', contentMd: 'y' })
      expect(a.slug).toBe('overview')
      expect(b.slug).toBe('overview')
      expect(a.id).not.toBe(b.id)
    })

    it('stores tags and autoGenerated flag', () => {
      const page = service.createPage({
        clientId: 'acme', title: 't', contentMd: 'body',
        tags: ['infra', 'k8s'], autoGenerated: true,
      })
      expect(page.tags).toEqual(['infra', 'k8s'])
      expect(page.autoGenerated).toBe(true)
    })
  })

  describe('getPage / listPages', () => {
    it('fetches by (clientId, slug)', () => {
      service.createPage({ clientId: 'acme', title: 'Ops Runbook', contentMd: 'x' })
      const found = service.getPage('acme', 'ops-runbook')
      expect(found).not.toBeNull()
      expect(found!.title).toBe('Ops Runbook')
    })

    it('returns null for missing page', () => {
      expect(service.getPage('acme', 'nope')).toBeNull()
    })

    it('lists pages scoped to client', () => {
      service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x' })
      service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x' })
      service.createPage({ clientId: 'beta', title: 'C', contentMd: 'x' })
      expect(service.listPages('acme')).toHaveLength(2)
      expect(service.listPages('beta')).toHaveLength(1)
    })

    it('filters by parentId', () => {
      const parent = service.createPage({ clientId: 'acme', title: 'Parent', contentMd: 'x' })
      service.createPage({ clientId: 'acme', title: 'Child', contentMd: 'x', parentId: parent.id })
      service.createPage({ clientId: 'acme', title: 'Top Level', contentMd: 'x' })

      const roots = service.listPages('acme', { parentId: null })
      expect(roots.map(p => p.title).sort()).toEqual(['Parent', 'Top Level'])

      const children = service.listPages('acme', { parentId: parent.id })
      expect(children).toHaveLength(1)
      expect(children[0].title).toBe('Child')
    })

    it('filters by tag', () => {
      service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x', tags: ['foo'] })
      service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x', tags: ['bar'] })
      const foo = service.listPages('acme', { tag: 'foo' })
      expect(foo).toHaveLength(1)
      expect(foo[0].title).toBe('A')
    })
  })

  describe('updatePage', () => {
    it('updates title and content, creates a new revision when content changes', () => {
      const page = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'v1' })
      const updated = service.updatePage(page.id, { title: 'A1', contentMd: 'v2' }, 'bob', 'bumped')
      expect(updated!.title).toBe('A1')
      expect(updated!.contentMd).toBe('v2')
      const history = service.getHistory(page.id)
      expect(history).toHaveLength(2)
      expect(history[0].changeSummary).toBe('bumped')
      expect(history[1].changeSummary).toBe('initial')
    })

    it('does not create a new revision when content is unchanged', () => {
      const page = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'v1' })
      service.updatePage(page.id, { title: 'A2' }, 'bob')
      expect(service.getHistory(page.id)).toHaveLength(1)
    })

    it('returns null for missing page', () => {
      expect(service.updatePage('missing-id', { title: 'x' })).toBeNull()
    })

    it('regenerates summary when content changes but summary is not supplied', () => {
      const page = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'first' })
      const updated = service.updatePage(page.id, { contentMd: 'second sentence here' })
      expect(updated!.summary).toContain('second sentence')
    })
  })

  describe('searchPages', () => {
    it('returns pages matching title, content or summary', () => {
      service.createPage({ clientId: 'acme', title: 'Database Setup', contentMd: 'postgres wal' })
      service.createPage({ clientId: 'acme', title: 'Frontend', contentMd: 'React tailwind' })
      service.createPage({ clientId: 'beta', title: 'Database Setup', contentMd: 'mysql' })

      const r1 = service.searchPages('acme', 'database')
      expect(r1).toHaveLength(1)
      expect(r1[0].title).toBe('Database Setup')

      const r2 = service.searchPages('acme', 'postgres')
      expect(r2).toHaveLength(1)

      const r3 = service.searchPages('acme', 'tailwind')
      expect(r3).toHaveLength(1)
      expect(r3[0].title).toBe('Frontend')

      expect(service.searchPages('acme', '')).toEqual([])
    })
  })

  describe('deletePageBySlug', () => {
    it('removes the page and its revisions and links', () => {
      const a = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x' })
      const b = service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x' })
      service.addLink(a.id, b.id)
      service.deletePageBySlug('acme', 'a')
      expect(service.getPage('acme', 'a')).toBeNull()
      expect(service.getHistory(a.id)).toHaveLength(0)
      expect(service.listLinks(a.id)).toHaveLength(0)
    })

    it('returns false when the page did not exist', () => {
      expect(service.deletePageBySlug('acme', 'nope')).toBe(false)
    })
  })

  describe('links & backlinks', () => {
    it('adds and lists outgoing links', () => {
      const a = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x' })
      const b = service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x' })
      service.addLink(a.id, b.id, 'mentions')
      service.addLink(a.id, b.id, 'depends')
      // add duplicate — INSERT OR IGNORE should make this a no-op
      service.addLink(a.id, b.id, 'mentions')
      const links = service.listLinks(a.id)
      expect(links).toHaveLength(2)
      const types = links.map(l => l.linkType).sort()
      expect(types).toEqual(['depends', 'mentions'])
    })

    it('buildBacklinks returns pages pointing to target within the client scope', () => {
      const a = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x' })
      const b = service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x' })
      const c = service.createPage({ clientId: 'acme', title: 'C', contentMd: 'x' })
      const d = service.createPage({ clientId: 'beta', title: 'D', contentMd: 'x' })
      service.addLink(a.id, c.id)
      service.addLink(b.id, c.id)
      service.addLink(d.id, c.id) // different client — must be excluded

      const backs = service.buildBacklinks('acme', c.id)
      expect(backs.map(p => p.title).sort()).toEqual(['A', 'B'])
    })

    it('removeLink removes a specific link type', () => {
      const a = service.createPage({ clientId: 'acme', title: 'A', contentMd: 'x' })
      const b = service.createPage({ clientId: 'acme', title: 'B', contentMd: 'x' })
      service.addLink(a.id, b.id, 'reference')
      service.addLink(a.id, b.id, 'mentions')
      service.removeLink(a.id, b.id, 'reference')
      expect(service.listLinks(a.id).map(l => l.linkType)).toEqual(['mentions'])
    })
  })
})

describe('markdown-render', () => {
  it('escapes raw HTML in content', () => {
    const html = renderMarkdown('<script>alert(1)</script>')
    expect(html).not.toContain('<script>')
    expect(html).toContain('&lt;script&gt;')
  })

  it('blocks javascript: URLs in links', () => {
    const html = renderMarkdown('[click](javascript:alert(1))')
    expect(html).toContain('href="#"')
    expect(html).not.toContain('javascript:')
  })

  it('renders headings, bold, inline code, and fenced code blocks', () => {
    const md = '# Title\n\nHello **world** and `code`.\n\n```ts\nconst x = 1\n```'
    const html = renderMarkdown(md)
    expect(html).toContain('<h1>Title</h1>')
    expect(html).toContain('<strong>world</strong>')
    expect(html).toContain('<code>code</code>')
    expect(html).toContain('<pre><code class="language-ts">const x = 1</code></pre>')
  })

  it('renders GFM tables', () => {
    const md = 'a | b\n---|---\n1 | 2'
    const html = renderMarkdown(md)
    expect(html).toContain('<table>')
    expect(html).toContain('<th>a</th>')
    expect(html).toContain('<td>1</td>')
  })

  it('renders unordered and ordered lists', () => {
    expect(renderMarkdown('- one\n- two')).toContain('<ul><li>one</li><li>two</li></ul>')
    expect(renderMarkdown('1. one\n2. two')).toContain('<ol><li>one</li><li>two</li></ol>')
  })

  it('escapeHtml handles quotes and ampersands', () => {
    expect(escapeHtml('<a href="x">&</a>')).toBe('&lt;a href=&quot;x&quot;&gt;&amp;&lt;/a&gt;')
  })

  it('summarize skips headings and code fences, truncates long text', () => {
    expect(summarize('# Title\n\nThe body text.')).toBe('The body text.')
    expect(summarize('```\ncode block\n```\nAfter fence.')).toBe('After fence.')
    const long = 'x'.repeat(500)
    const s = summarize(long, 50)
    expect(s.length).toBe(50)
    expect(s.endsWith('…')).toBe(true)
  })
})
