// Part of eYssen. See LICENSE file for full copyright and licensing details.

import { effectiveProjectId } from '@modules/memory/types.js'
import type {
  ClientWikiPage, CreatePageInput, UpdatePageInput,
} from './types.js'
import {
  ticketSlug, decisionSlug, parseWikiTicketBody,
  type WikiProjectSettings, type WikiTicketBody,
} from './wiki-paths.js'

export interface StageChangedEvent {
  conversationId: string
  toStageId: string | null
}

interface TicketConversation {
  id: string
  title: string | null
  projectId: string | null
  messages: Array<{ role: string; content: string }>
}

interface ClosedStage {
  id: string
  isClosed: boolean
}

export interface WikiAutoUpdateDeps {
  wiki: {
    getPage(clientId: string, slug: string): ClientWikiPage | null
    createPage(input: CreatePageInput): ClientWikiPage
    updatePage(id: string, updates: UpdatePageInput, author?: string, changeSummary?: string): ClientWikiPage | null
  }
  conversations?: { get(id: string): TicketConversation | null }
  stages?: { get(id: string): ClosedStage | null }
  projects?: { get(id: string): WikiProjectSettings | null }
  logger?: { debug?: (o: unknown, m?: string) => void; warn?: (o: unknown, m?: string) => void; info?: (o: unknown, m?: string) => void }
  /** Injected only so tests can prove auto-update never reads the vault. */
  vault?: { read: (path: string) => unknown }
}

interface TeamSessionLike {
  id: string
  parentConversationId: string
  createdAt: string
  completedAt: string | null
}

interface TeamMemoryLike {
  category: string
  key: string
  value: string
  authorAgentId: string | null
}

const AUTHOR = 'wiki-auto-update'
const DECISION_CATEGORIES = new Set(['finding', 'decision'])

function parseValue(raw: string): string {
  try {
    const parsed = JSON.parse(raw)
    if (typeof parsed === 'string') return parsed
    return JSON.stringify(parsed, null, 2)
  } catch {
    return raw
  }
}

function lastTurn(messages: TicketConversation['messages'], role: string) {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === role && (messages[i].content ?? '').trim()) return messages[i]
  }
  return null
}

function ticketMarkdown(conv: TicketConversation, body: WikiTicketBody): string {
  const header = [
    `# ${conv.title?.trim() || 'Untitled ticket'}`,
    '',
    `- Ticket: \`${conv.id}\``,
  ]
  if (body === 'title') return header.join('\n') + '\n'

  const nonempty = conv.messages.filter((m) => (m.content ?? '').trim())
  const latest = body === 'latest'
    ? new Set([lastTurn(nonempty, 'user'), lastTurn(nonempty, 'assistant')].filter(Boolean))
    : null
  const selected = latest ? nonempty.filter((m) => latest.has(m)) : nonempty

  const lines = [...header, '', '## Conversation', '']
  for (const m of selected) {
    lines.push(`**${m.role}:**`, '', m.content.trim(), '')
  }
  return lines.join('\n').trimEnd() + '\n'
}

function decisionMarkdown(session: TeamSessionLike, keep: TeamMemoryLike[]): string {
  const byCategory = new Map<string, TeamMemoryLike[]>()
  for (const e of keep) {
    const arr = byCategory.get(e.category) ?? []
    arr.push(e)
    byCategory.set(e.category, arr)
  }
  const sections: string[] = []
  for (const [cat, items] of byCategory) {
    sections.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}s`, '')
    for (const item of items) {
      sections.push(`### ${item.key}`)
      sections.push(`*${item.authorAgentId ?? 'system'}*`, '')
      sections.push(parseValue(item.value), '')
    }
  }
  return [
    `# Team session ${session.id}`,
    '',
    `- Session: \`${session.id}\``,
    `- Conversation: \`${session.parentConversationId}\``,
    `- Started: ${session.createdAt}`,
    `- Completed: ${session.completedAt ?? '(in progress)'}`,
    '',
    ...sections,
  ].join('\n')
}

const OFF: WikiProjectSettings = {
  wikiAutoTickets: false,
  wikiAutoDecisions: false,
  wikiTicketBody: 'title',
}

export function createWikiAutoUpdate(deps: WikiAutoUpdateDeps) {
  const { wiki, conversations, stages, projects, logger } = deps

  function settingsFor(projectId: string): WikiProjectSettings {
    const row = projects?.get(projectId)
    if (!row) return OFF
    return {
      wikiAutoTickets: !!row.wikiAutoTickets,
      wikiAutoDecisions: !!row.wikiAutoDecisions,
      wikiTicketBody: parseWikiTicketBody(row.wikiTicketBody),
    }
  }

  function upsertAutoPage(input: {
    projectId: string
    slug: string
    title: string
    contentMd: string
    changeSummary: string
    tags: string[]
  }): boolean {
    const existing = wiki.getPage(input.projectId, input.slug)
    if (existing) {
      if (!existing.autoGenerated) {
        logger?.debug?.(
          { slug: input.slug, projectId: input.projectId },
          'Wiki auto-update skipped — human owns the page',
        )
        return false
      }
      wiki.updatePage(
        existing.id,
        {
          title: input.title,
          contentMd: input.contentMd,
          autoGenerated: true,
          tags: input.tags,
        },
        AUTHOR,
        input.changeSummary,
      )
      return true
    }
    wiki.createPage({
      clientId: input.projectId,
      slug: input.slug,
      title: input.title,
      contentMd: input.contentMd,
      autoGenerated: true,
      author: AUTHOR,
      tags: input.tags,
    })
    return true
  }

  function recordDecision(input: {
    projectId: string | null
    sourceId: string
    title: string
    body: string
  }): { wrote: boolean } {
    const projectId = effectiveProjectId(input.projectId)
    if (!projectId) return { wrote: false }
    const wrote = upsertAutoPage({
      projectId,
      slug: decisionSlug(input.sourceId),
      title: input.title,
      contentMd: input.body,
      changeSummary: 'team session decision',
      tags: ['decision', 'auto'],
    })
    return { wrote }
  }

  return {
    upsertAutoPage,
    recordDecision,

    handleStageChanged(evt: StageChangedEvent): { wrote: boolean } {
      const conversationId = evt?.conversationId
      const toStageId = evt?.toStageId
      if (!conversationId || !toStageId) return { wrote: false }
      const stage = stages?.get(toStageId)
      if (!stage?.isClosed) return { wrote: false }
      const conv = conversations?.get(conversationId)
      if (!conv) return { wrote: false }
      const projectId = effectiveProjectId(conv.projectId)
      if (!projectId) return { wrote: false }
      const settings = settingsFor(projectId)
      if (!settings.wikiAutoTickets) return { wrote: false }
      const wrote = upsertAutoPage({
        projectId,
        slug: ticketSlug(conv.id),
        title: conv.title?.trim() || 'Untitled ticket',
        contentMd: ticketMarkdown(conv, settings.wikiTicketBody),
        changeSummary: 'ticket closed',
        tags: ['ticket', 'auto'],
      })
      return { wrote }
    },

    /**
     * One truth: a project-scoped session lands on the wiki, not the vault.
     * Projectless sessions keep the existing vault promoter.
     */
    promoteTeamSession(input: {
      projectId: string | null
      session: TeamSessionLike
      entries: TeamMemoryLike[]
      vaultPromote: () => { path: string } | null
    }): 'wiki' | 'vault' | 'none' {
      const keep = input.entries.filter((e) => DECISION_CATEGORIES.has(e.category))
      if (keep.length === 0) return 'none'
      const projectId = effectiveProjectId(input.projectId)
      if (projectId && settingsFor(projectId).wikiAutoDecisions) {
        const { wrote } = recordDecision({
          projectId,
          sourceId: input.session.id,
          title: `Team session ${input.session.id.slice(0, 8)}`,
          body: decisionMarkdown(input.session, keep),
        })
        return wrote ? 'wiki' : 'none'
      }
      input.vaultPromote()
      return 'vault'
    },
  }
}

export type WikiAutoUpdate = ReturnType<typeof createWikiAutoUpdate>
