// Part of eYssen. See LICENSE file for full copyright and licensing details.

import type { Hono } from 'hono'
import type { Logger } from 'pino'
import { requirePermission } from '@modules/permissions/middleware'
import type { ClientWikiService } from './wiki-service.js'
import { UniqueSlugError } from './wiki-service.js'
import { renderMarkdown } from './markdown-render.js'

const SUBJECT = 'ClientWikiPage'

export function createClientWikiRoutes(app: Hono<any>, service: ClientWikiService, logger: Logger) {
  // List pages for a client
  app.get('/api/v1/client-wiki/:clientId/pages', requirePermission('read', SUBJECT), (c) => {
    const clientId = c.req.param('clientId')
    const parentIdQ = c.req.query('parentId')
    const tag = c.req.query('tag')
    const opts: { parentId?: string | null; tag?: string } = {}
    if (parentIdQ !== undefined) opts.parentId = parentIdQ === 'null' || parentIdQ === '' ? null : parentIdQ
    if (tag) opts.tag = tag
    return c.json(service.listPages(clientId, opts))
  })

  // Search
  app.get('/api/v1/client-wiki/:clientId/search', requirePermission('read', SUBJECT), (c) => {
    const clientId = c.req.param('clientId')
    const q = c.req.query('q') ?? ''
    return c.json(service.searchPages(clientId, q))
  })

  // Read page
  app.get('/api/v1/client-wiki/:clientId/pages/:slug', requirePermission('read', SUBJECT), (c) => {
    const page = service.getPage(c.req.param('clientId'), c.req.param('slug'))
    if (!page) return c.json({ error: 'Page not found' }, 404)
    const render = c.req.query('render')
    if (render === 'html') {
      return c.json({ ...page, html: renderMarkdown(page.contentMd) })
    }
    return c.json(page)
  })

  // Get page revision history
  app.get('/api/v1/client-wiki/:clientId/pages/:slug/history', requirePermission('read', SUBJECT), (c) => {
    const page = service.getPage(c.req.param('clientId'), c.req.param('slug'))
    if (!page) return c.json({ error: 'Page not found' }, 404)
    return c.json(service.getHistory(page.id))
  })

  // Backlinks
  app.get('/api/v1/client-wiki/:clientId/pages/:slug/backlinks', requirePermission('read', SUBJECT), (c) => {
    const clientId = c.req.param('clientId')
    const page = service.getPage(clientId, c.req.param('slug'))
    if (!page) return c.json({ error: 'Page not found' }, 404)
    return c.json(service.buildBacklinks(clientId, page.id))
  })

  // Create page
  app.post('/api/v1/client-wiki/:clientId/pages', requirePermission('create', SUBJECT), async (c) => {
    const clientId = c.req.param('clientId')
    const body = await c.req.json().catch(() => null)
    if (!body || typeof body !== 'object') return c.json({ error: 'Invalid JSON body' }, 400)
    if (!body.title || typeof body.title !== 'string') return c.json({ error: 'title is required' }, 400)
    if (body.contentMd === undefined || typeof body.contentMd !== 'string') return c.json({ error: 'contentMd is required' }, 400)

    try {
      const page = service.createPage({
        clientId,
        title: body.title,
        contentMd: body.contentMd,
        slug: body.slug,
        summary: body.summary,
        tags: Array.isArray(body.tags) ? body.tags : undefined,
        parentId: body.parentId ?? null,
        author: body.author,
        autoGenerated: !!body.autoGenerated,
      })
      return c.json(page, 201)
    } catch (err) {
      if (err instanceof UniqueSlugError) return c.json({ error: err.message }, 409)
      throw err
    }
  })

  // Update page
  app.put('/api/v1/client-wiki/:clientId/pages/:slug', requirePermission('update', SUBJECT), async (c) => {
    const clientId = c.req.param('clientId')
    const slug = c.req.param('slug')
    const page = service.getPage(clientId, slug)
    if (!page) return c.json({ error: 'Page not found' }, 404)

    const body = await c.req.json().catch(() => null)
    if (!body || typeof body !== 'object') return c.json({ error: 'Invalid JSON body' }, 400)

    const updated = service.updatePage(
      page.id,
      {
        title: body.title,
        contentMd: body.contentMd,
        summary: body.summary,
        tags: Array.isArray(body.tags) ? body.tags : undefined,
        parentId: body.parentId,
        // HTTP updates are human/API writes. Omit or false takes ownership so
        // auto-update will not overwrite; pass true only when a machine write
        // goes through this route on purpose.
        autoGenerated: body.autoGenerated === true,
      },
      body.author,
      body.changeSummary,
    )
    return c.json(updated)
  })

  // Delete page
  app.delete('/api/v1/client-wiki/:clientId/pages/:slug', requirePermission('delete', SUBJECT), (c) => {
    const ok = service.deletePageBySlug(c.req.param('clientId'), c.req.param('slug'))
    if (!ok) return c.json({ error: 'Page not found' }, 404)
    return c.body(null, 204)
  })

  logger.info('Client wiki routes registered')
}
