// Part of eYssen. See LICENSE file for full copyright and licensing details.

// --- Page ---

export interface ClientWikiPage {
  id: string
  clientId: string
  slug: string
  title: string
  contentMd: string
  summary: string | null
  tags: string[]
  parentId: string | null
  createdAt: number
  updatedAt: number
  updatedBy: string | null
  autoGenerated: boolean
}

export interface CreatePageInput {
  clientId: string
  title: string
  contentMd: string
  slug?: string
  summary?: string
  tags?: string[]
  parentId?: string | null
  author?: string
  autoGenerated?: boolean
}

export interface UpdatePageInput {
  title?: string
  contentMd?: string
  summary?: string
  tags?: string[]
  parentId?: string | null
  autoGenerated?: boolean
}

export interface ListPageOpts {
  parentId?: string | null
  tag?: string
}

// --- Revision ---

export interface ClientWikiRevision {
  id: number
  pageId: string
  contentMd: string
  ts: number
  author: string | null
  changeSummary: string | null
}

// --- Links ---

export type LinkType = 'reference' | 'mentions' | 'depends'

export interface ClientWikiLink {
  fromPage: string
  toPage: string
  linkType: LinkType
}
