// Part of eYssen. See LICENSE file for full copyright and licensing details.

import { sql } from 'drizzle-orm'
import { generateId } from '@shared/crypto'
import type { EyasDb } from '@core/types'
import type {
  ClientWikiPage, CreatePageInput, UpdatePageInput, ListPageOpts,
  ClientWikiRevision, ClientWikiLink, LinkType,
} from './types.js'
import { summarize } from './markdown-render.js'

function toSlug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 100) || 'untitled'
}

function rowToPage(r: any): ClientWikiPage {
  let tags: string[] = []
  try { tags = JSON.parse(r.tags ?? '[]') } catch { tags = [] }
  return {
    id: r.id,
    clientId: r.client_id,
    slug: r.slug,
    title: r.title,
    contentMd: r.content_md,
    summary: r.summary,
    tags,
    parentId: r.parent_id,
    createdAt: Number(r.created_at),
    updatedAt: Number(r.updated_at),
    updatedBy: r.updated_by,
    autoGenerated: !!r.auto_generated,
  }
}

function rowToRevision(r: any): ClientWikiRevision {
  return {
    id: Number(r.id),
    pageId: r.page_id,
    contentMd: r.content_md,
    ts: Number(r.ts),
    author: r.author,
    changeSummary: r.change_summary,
  }
}

export class UniqueSlugError extends Error {
  constructor(clientId: string, slug: string) {
    super(`Page with slug '${slug}' already exists for client '${clientId}'`)
    this.name = 'UniqueSlugError'
  }
}

export function createClientWikiService(db: EyasDb) {
  return {
    // --- Pages ---

    createPage(input: CreatePageInput): ClientWikiPage {
      const id = generateId()
      const now = Date.now()
      const slug = input.slug ? toSlug(input.slug) : toSlug(input.title)
      const tags = JSON.stringify(input.tags ?? [])
      const summary = input.summary ?? summarize(input.contentMd)
      const autoGenerated = input.autoGenerated ? 1 : 0

      const existing = (db as any).all(
        sql`SELECT id FROM client_wiki_pages WHERE client_id = ${input.clientId} AND slug = ${slug}`,
      ) as any[]
      if (existing.length > 0) throw new UniqueSlugError(input.clientId, slug)

      db.run(sql`INSERT INTO client_wiki_pages
        (id, client_id, slug, title, content_md, summary, tags, parent_id, created_at, updated_at, updated_by, auto_generated)
        VALUES (${id}, ${input.clientId}, ${slug}, ${input.title}, ${input.contentMd}, ${summary},
                ${tags}, ${input.parentId ?? null}, ${now}, ${now}, ${input.author ?? null}, ${autoGenerated})`)

      db.run(sql`INSERT INTO client_wiki_revisions (page_id, content_md, ts, author, change_summary)
        VALUES (${id}, ${input.contentMd}, ${now}, ${input.author ?? null}, ${'initial'})`)

      return this.getPageById(id)!
    },

    updatePage(id: string, updates: UpdatePageInput, author?: string, changeSummary?: string): ClientWikiPage | null {
      const page = this.getPageById(id)
      if (!page) return null

      const now = Date.now()
      const title = updates.title ?? page.title
      const contentMd = updates.contentMd ?? page.contentMd
      const summary = updates.summary !== undefined
        ? updates.summary
        : (updates.contentMd !== undefined ? summarize(updates.contentMd) : page.summary)
      const tags = updates.tags !== undefined ? JSON.stringify(updates.tags) : JSON.stringify(page.tags)
      const parentId = updates.parentId !== undefined ? updates.parentId : page.parentId
      const autoGenerated = updates.autoGenerated !== undefined ? (updates.autoGenerated ? 1 : 0) : (page.autoGenerated ? 1 : 0)

      db.run(sql`UPDATE client_wiki_pages SET
        title = ${title},
        content_md = ${contentMd},
        summary = ${summary},
        tags = ${tags},
        parent_id = ${parentId},
        updated_at = ${now},
        updated_by = ${author ?? null},
        auto_generated = ${autoGenerated}
        WHERE id = ${id}`)

      if (updates.contentMd !== undefined && updates.contentMd !== page.contentMd) {
        db.run(sql`INSERT INTO client_wiki_revisions (page_id, content_md, ts, author, change_summary)
          VALUES (${id}, ${contentMd}, ${now}, ${author ?? null}, ${changeSummary ?? null})`)
      }

      return this.getPageById(id)
    },

    getPage(clientId: string, slug: string): ClientWikiPage | null {
      const rows = (db as any).all(
        sql`SELECT * FROM client_wiki_pages WHERE client_id = ${clientId} AND slug = ${slug}`,
      ) as any[]
      return rows.length > 0 ? rowToPage(rows[0]) : null
    },

    getPageById(id: string): ClientWikiPage | null {
      const rows = (db as any).all(sql`SELECT * FROM client_wiki_pages WHERE id = ${id}`) as any[]
      return rows.length > 0 ? rowToPage(rows[0]) : null
    },

    listPages(clientId: string, opts: ListPageOpts = {}): ClientWikiPage[] {
      let rows: any[]
      if (opts.parentId !== undefined) {
        if (opts.parentId === null) {
          rows = (db as any).all(
            sql`SELECT * FROM client_wiki_pages WHERE client_id = ${clientId} AND parent_id IS NULL ORDER BY title`,
          ) as any[]
        } else {
          rows = (db as any).all(
            sql`SELECT * FROM client_wiki_pages WHERE client_id = ${clientId} AND parent_id = ${opts.parentId} ORDER BY title`,
          ) as any[]
        }
      } else {
        rows = (db as any).all(
          sql`SELECT * FROM client_wiki_pages WHERE client_id = ${clientId} ORDER BY title`,
        ) as any[]
      }
      let pages = rows.map(rowToPage)
      if (opts.tag) {
        pages = pages.filter(p => p.tags.includes(opts.tag!))
      }
      return pages
    },

    searchPages(clientId: string, query: string): ClientWikiPage[] {
      if (!query || !query.trim()) return []
      const like = `%${query.trim()}%`
      const rows = (db as any).all(
        sql`SELECT * FROM client_wiki_pages
            WHERE client_id = ${clientId}
              AND (title LIKE ${like} OR content_md LIKE ${like} OR summary LIKE ${like})
            ORDER BY updated_at DESC`,
      ) as any[]
      return rows.map(rowToPage)
    },

    deletePageBySlug(clientId: string, slug: string): boolean {
      const page = this.getPage(clientId, slug)
      if (!page) return false
      db.run(sql`DELETE FROM client_wiki_links WHERE from_page = ${page.id} OR to_page = ${page.id}`)
      db.run(sql`DELETE FROM client_wiki_revisions WHERE page_id = ${page.id}`)
      db.run(sql`DELETE FROM client_wiki_pages WHERE id = ${page.id}`)
      return true
    },

    // --- Revisions ---

    getHistory(pageId: string): ClientWikiRevision[] {
      // Order by ts DESC with id DESC as tiebreaker (autoincrement id is monotonic, so
      // same-millisecond inserts still sort correctly).
      return ((db as any).all(
        sql`SELECT * FROM client_wiki_revisions WHERE page_id = ${pageId} ORDER BY ts DESC, id DESC`,
      ) as any[]).map(rowToRevision)
    },

    // --- Links & backlinks ---

    addLink(fromPage: string, toPage: string, linkType: LinkType = 'reference'): void {
      db.run(sql`INSERT OR IGNORE INTO client_wiki_links (from_page, to_page, link_type)
        VALUES (${fromPage}, ${toPage}, ${linkType})`)
    },

    removeLink(fromPage: string, toPage: string, linkType?: LinkType): void {
      if (linkType) {
        db.run(sql`DELETE FROM client_wiki_links
          WHERE from_page = ${fromPage} AND to_page = ${toPage} AND link_type = ${linkType}`)
      } else {
        db.run(sql`DELETE FROM client_wiki_links
          WHERE from_page = ${fromPage} AND to_page = ${toPage}`)
      }
    },

    listLinks(fromPage: string): ClientWikiLink[] {
      return ((db as any).all(sql`SELECT * FROM client_wiki_links WHERE from_page = ${fromPage}`) as any[]).map(r => ({
        fromPage: r.from_page, toPage: r.to_page, linkType: r.link_type as LinkType,
      }))
    },

    /**
     * Pages that link TO the given page, scoped to the given client.
     */
    buildBacklinks(clientId: string, pageId: string): ClientWikiPage[] {
      const rows = (db as any).all(
        sql`SELECT p.* FROM client_wiki_pages p
            INNER JOIN client_wiki_links l ON l.from_page = p.id
            WHERE l.to_page = ${pageId} AND p.client_id = ${clientId}
            ORDER BY p.title`,
      ) as any[]
      return rows.map(rowToPage)
    },
  }
}

export type ClientWikiService = ReturnType<typeof createClientWikiService>
