/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as UsersRouteImport } from './users'
import { Route as ToolsRouteImport } from './tools'
import { Route as SkillsRouteImport } from './skills'
import { Route as SkillEvolutionRouteImport } from './skill-evolution'
import { Route as SetupRouteImport } from './setup'
import { Route as SettingsRouteImport } from './settings'
import { Route as SelfLearningRouteImport } from './self-learning'
import { Route as SecurityRouteImport } from './security'
import { Route as SecretsRouteImport } from './secrets'
import { Route as SearchSourcesRouteImport } from './search-sources'
import { Route as SearchResultsRouteImport } from './search-results'
import { Route as SchedulerRouteImport } from './scheduler'
import { Route as ResearchRouteImport } from './research'
import { Route as ProvidersRouteImport } from './providers'
import { Route as PromptsRouteImport } from './prompts'
import { Route as PromptSettingsRouteImport } from './prompt-settings'
import { Route as ProjectsRouteImport } from './projects'
import { Route as ProactiveRouteImport } from './proactive'
import { Route as PrivacyRouteImport } from './privacy'
import { Route as PipelinesRouteImport } from './pipelines'
import { Route as OpsRouteImport } from './ops'
import { Route as ObservabilityRouteImport } from './observability'
import { Route as NotificationsSettingsRouteImport } from './notifications-settings'
import { Route as NodesRouteImport } from './nodes'
import { Route as MissionControlRouteImport } from './mission-control'
import { Route as MemoryRouteImport } from './memory'
import { Route as MeetingsRouteImport } from './meetings'
import { Route as McpSettingsRouteImport } from './mcp-settings'
import { Route as LoginRouteImport } from './login'
import { Route as KnowledgeRouteImport } from './knowledge'
import { Route as IngressRouteImport } from './ingress'
import { Route as HandsRouteImport } from './hands'
import { Route as ForgeRouteImport } from './forge'
import { Route as ExtensionsRouteImport } from './extensions'
import { Route as DocumentsSettingsRouteImport } from './documents-settings'
import { Route as DocumentsRouteImport } from './documents'
import { Route as DesignRouteImport } from './design'
import { Route as ConversationsRouteImport } from './conversations'
import { Route as ConnectionsRouteImport } from './connections'
import { Route as CommunicationRouteImport } from './communication'
import { Route as BoardRouteImport } from './board'
import { Route as BackupRouteImport } from './backup'
import { Route as AutonomyRouteImport } from './autonomy'
import { Route as AuditRouteImport } from './audit'
import { Route as ApiKeysRouteImport } from './api-keys'
import { Route as AgentsRouteImport } from './agents'
import { Route as AgentRunsRouteImport } from './agent-runs'
import { Route as IndexRouteImport } from './index'
import { Route as AgentsIndexRouteImport } from './agents.index'
import { Route as PipelinesRunIdRouteImport } from './pipelines.$runId'
import { Route as KnowledgePageIdRouteImport } from './knowledge.$pageId'
import { Route as DesignDesignIdRouteImport } from './design.$designId'
import { Route as ConversationsConversationIdRouteImport } from './conversations.$conversationId'
import { Route as AgentsAgentIdRouteImport } from './agents.$agentId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillEvolutionRoute = SkillEvolutionRouteImport.update({
  id: '/skill-evolution',
  path: '/skill-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfLearningRoute = SelfLearningRouteImport.update({
  id: '/self-learning',
  path: '/self-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchSourcesRoute = SearchSourcesRouteImport.update({
  id: '/search-sources',
  path: '/search-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSettingsRoute = PromptSettingsRouteImport.update({
  id: '/prompt-settings',
  path: '/prompt-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProactiveRoute = ProactiveRouteImport.update({
  id: '/proactive',
  path: '/proactive',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications-settings',
  path: '/notifications-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSettingsRoute = McpSettingsRouteImport.update({
  id: '/mcp-settings',
  path: '/mcp-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IngressRoute = IngressRouteImport.update({
  id: '/ingress',
  path: '/ingress',
  getParentRoute: () => rootRouteImport,
} as any)
const HandsRoute = HandsRouteImport.update({
  id: '/hands',
  path: '/hands',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSettingsRoute = DocumentsSettingsRouteImport.update({
  id: '/documents-settings',
  path: '/documents-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomyRoute = AutonomyRouteImport.update({
  id: '/autonomy',
  path: '/autonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const PipelinesRunIdRoute = PipelinesRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => PipelinesRoute,
} as any)
const KnowledgePageIdRoute = KnowledgePageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const DesignDesignIdRoute = DesignDesignIdRouteImport.update({
  id: '/$designId',
  path: '/$designId',
  getParentRoute: () => DesignRoute,
} as any)
const ConversationsConversationIdRoute =
  ConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ConversationsRoute,
  } as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/agents': typeof AgentsRouteWithChildren
  '/api-keys': typeof ApiKeysRoute
  '/audit': typeof AuditRoute
  '/autonomy': typeof AutonomyRoute
  '/backup': typeof BackupRoute
  '/board': typeof BoardRoute
  '/communication': typeof CommunicationRoute
  '/connections': typeof ConnectionsRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/documents-settings': typeof DocumentsSettingsRoute
  '/extensions': typeof ExtensionsRoute
  '/forge': typeof ForgeRoute
  '/hands': typeof HandsRoute
  '/ingress': typeof IngressRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp-settings': typeof McpSettingsRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/mission-control': typeof MissionControlRoute
  '/nodes': typeof NodesRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/observability': typeof ObservabilityRoute
  '/ops': typeof OpsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/proactive': typeof ProactiveRoute
  '/projects': typeof ProjectsRoute
  '/prompt-settings': typeof PromptSettingsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/research': typeof ResearchRoute
  '/scheduler': typeof SchedulerRoute
  '/search-results': typeof SearchResultsRoute
  '/search-sources': typeof SearchSourcesRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/self-learning': typeof SelfLearningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skill-evolution': typeof SkillEvolutionRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/knowledge/$pageId': typeof KnowledgePageIdRoute
  '/pipelines/$runId': typeof PipelinesRunIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit': typeof AuditRoute
  '/autonomy': typeof AutonomyRoute
  '/backup': typeof BackupRoute
  '/board': typeof BoardRoute
  '/communication': typeof CommunicationRoute
  '/connections': typeof ConnectionsRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/documents-settings': typeof DocumentsSettingsRoute
  '/extensions': typeof ExtensionsRoute
  '/forge': typeof ForgeRoute
  '/hands': typeof HandsRoute
  '/ingress': typeof IngressRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp-settings': typeof McpSettingsRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/mission-control': typeof MissionControlRoute
  '/nodes': typeof NodesRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/observability': typeof ObservabilityRoute
  '/ops': typeof OpsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/proactive': typeof ProactiveRoute
  '/projects': typeof ProjectsRoute
  '/prompt-settings': typeof PromptSettingsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/research': typeof ResearchRoute
  '/scheduler': typeof SchedulerRoute
  '/search-results': typeof SearchResultsRoute
  '/search-sources': typeof SearchSourcesRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/self-learning': typeof SelfLearningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skill-evolution': typeof SkillEvolutionRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/knowledge/$pageId': typeof KnowledgePageIdRoute
  '/pipelines/$runId': typeof PipelinesRunIdRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/agents': typeof AgentsRouteWithChildren
  '/api-keys': typeof ApiKeysRoute
  '/audit': typeof AuditRoute
  '/autonomy': typeof AutonomyRoute
  '/backup': typeof BackupRoute
  '/board': typeof BoardRoute
  '/communication': typeof CommunicationRoute
  '/connections': typeof ConnectionsRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/documents-settings': typeof DocumentsSettingsRoute
  '/extensions': typeof ExtensionsRoute
  '/forge': typeof ForgeRoute
  '/hands': typeof HandsRoute
  '/ingress': typeof IngressRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp-settings': typeof McpSettingsRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/mission-control': typeof MissionControlRoute
  '/nodes': typeof NodesRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/observability': typeof ObservabilityRoute
  '/ops': typeof OpsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/proactive': typeof ProactiveRoute
  '/projects': typeof ProjectsRoute
  '/prompt-settings': typeof PromptSettingsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/research': typeof ResearchRoute
  '/scheduler': typeof SchedulerRoute
  '/search-results': typeof SearchResultsRoute
  '/search-sources': typeof SearchSourcesRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/self-learning': typeof SelfLearningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skill-evolution': typeof SkillEvolutionRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/knowledge/$pageId': typeof KnowledgePageIdRoute
  '/pipelines/$runId': typeof PipelinesRunIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-runs'
    | '/agents'
    | '/api-keys'
    | '/audit'
    | '/autonomy'
    | '/backup'
    | '/board'
    | '/communication'
    | '/connections'
    | '/conversations'
    | '/design'
    | '/documents'
    | '/documents-settings'
    | '/extensions'
    | '/forge'
    | '/hands'
    | '/ingress'
    | '/knowledge'
    | '/login'
    | '/mcp-settings'
    | '/meetings'
    | '/memory'
    | '/mission-control'
    | '/nodes'
    | '/notifications-settings'
    | '/observability'
    | '/ops'
    | '/pipelines'
    | '/privacy'
    | '/proactive'
    | '/projects'
    | '/prompt-settings'
    | '/prompts'
    | '/providers'
    | '/research'
    | '/scheduler'
    | '/search-results'
    | '/search-sources'
    | '/secrets'
    | '/security'
    | '/self-learning'
    | '/settings'
    | '/setup'
    | '/skill-evolution'
    | '/skills'
    | '/tools'
    | '/users'
    | '/agents/$agentId'
    | '/conversations/$conversationId'
    | '/design/$designId'
    | '/knowledge/$pageId'
    | '/pipelines/$runId'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-runs'
    | '/api-keys'
    | '/audit'
    | '/autonomy'
    | '/backup'
    | '/board'
    | '/communication'
    | '/connections'
    | '/conversations'
    | '/design'
    | '/documents'
    | '/documents-settings'
    | '/extensions'
    | '/forge'
    | '/hands'
    | '/ingress'
    | '/knowledge'
    | '/login'
    | '/mcp-settings'
    | '/meetings'
    | '/memory'
    | '/mission-control'
    | '/nodes'
    | '/notifications-settings'
    | '/observability'
    | '/ops'
    | '/pipelines'
    | '/privacy'
    | '/proactive'
    | '/projects'
    | '/prompt-settings'
    | '/prompts'
    | '/providers'
    | '/research'
    | '/scheduler'
    | '/search-results'
    | '/search-sources'
    | '/secrets'
    | '/security'
    | '/self-learning'
    | '/settings'
    | '/setup'
    | '/skill-evolution'
    | '/skills'
    | '/tools'
    | '/users'
    | '/agents/$agentId'
    | '/conversations/$conversationId'
    | '/design/$designId'
    | '/knowledge/$pageId'
    | '/pipelines/$runId'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/agent-runs'
    | '/agents'
    | '/api-keys'
    | '/audit'
    | '/autonomy'
    | '/backup'
    | '/board'
    | '/communication'
    | '/connections'
    | '/conversations'
    | '/design'
    | '/documents'
    | '/documents-settings'
    | '/extensions'
    | '/forge'
    | '/hands'
    | '/ingress'
    | '/knowledge'
    | '/login'
    | '/mcp-settings'
    | '/meetings'
    | '/memory'
    | '/mission-control'
    | '/nodes'
    | '/notifications-settings'
    | '/observability'
    | '/ops'
    | '/pipelines'
    | '/privacy'
    | '/proactive'
    | '/projects'
    | '/prompt-settings'
    | '/prompts'
    | '/providers'
    | '/research'
    | '/scheduler'
    | '/search-results'
    | '/search-sources'
    | '/secrets'
    | '/security'
    | '/self-learning'
    | '/settings'
    | '/setup'
    | '/skill-evolution'
    | '/skills'
    | '/tools'
    | '/users'
    | '/agents/$agentId'
    | '/conversations/$conversationId'
    | '/design/$designId'
    | '/knowledge/$pageId'
    | '/pipelines/$runId'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunsRoute: typeof AgentRunsRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApiKeysRoute: typeof ApiKeysRoute
  AuditRoute: typeof AuditRoute
  AutonomyRoute: typeof AutonomyRoute
  BackupRoute: typeof BackupRoute
  BoardRoute: typeof BoardRoute
  CommunicationRoute: typeof CommunicationRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  DesignRoute: typeof DesignRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  DocumentsSettingsRoute: typeof DocumentsSettingsRoute
  ExtensionsRoute: typeof ExtensionsRoute
  ForgeRoute: typeof ForgeRoute
  HandsRoute: typeof HandsRoute
  IngressRoute: typeof IngressRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpSettingsRoute: typeof McpSettingsRoute
  MeetingsRoute: typeof MeetingsRoute
  MemoryRoute: typeof MemoryRoute
  MissionControlRoute: typeof MissionControlRoute
  NodesRoute: typeof NodesRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OpsRoute: typeof OpsRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProactiveRoute: typeof ProactiveRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptSettingsRoute: typeof PromptSettingsRoute
  PromptsRoute: typeof PromptsRoute
  ProvidersRoute: typeof ProvidersRoute
  ResearchRoute: typeof ResearchRoute
  SchedulerRoute: typeof SchedulerRoute
  SearchResultsRoute: typeof SearchResultsRoute
  SearchSourcesRoute: typeof SearchSourcesRoute
  SecretsRoute: typeof SecretsRoute
  SecurityRoute: typeof SecurityRoute
  SelfLearningRoute: typeof SelfLearningRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SkillEvolutionRoute: typeof SkillEvolutionRoute
  SkillsRoute: typeof SkillsRoute
  ToolsRoute: typeof ToolsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-evolution': {
      id: '/skill-evolution'
      path: '/skill-evolution'
      fullPath: '/skill-evolution'
      preLoaderRoute: typeof SkillEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-learning': {
      id: '/self-learning'
      path: '/self-learning'
      fullPath: '/self-learning'
      preLoaderRoute: typeof SelfLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-sources': {
      id: '/search-sources'
      path: '/search-sources'
      fullPath: '/search-sources'
      preLoaderRoute: typeof SearchSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-settings': {
      id: '/prompt-settings'
      path: '/prompt-settings'
      fullPath: '/prompt-settings'
      preLoaderRoute: typeof PromptSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proactive': {
      id: '/proactive'
      path: '/proactive'
      fullPath: '/proactive'
      preLoaderRoute: typeof ProactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications-settings': {
      id: '/notifications-settings'
      path: '/notifications-settings'
      fullPath: '/notifications-settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-settings': {
      id: '/mcp-settings'
      path: '/mcp-settings'
      fullPath: '/mcp-settings'
      preLoaderRoute: typeof McpSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingress': {
      id: '/ingress'
      path: '/ingress'
      fullPath: '/ingress'
      preLoaderRoute: typeof IngressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hands': {
      id: '/hands'
      path: '/hands'
      fullPath: '/hands'
      preLoaderRoute: typeof HandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents-settings': {
      id: '/documents-settings'
      path: '/documents-settings'
      fullPath: '/documents-settings'
      preLoaderRoute: typeof DocumentsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomy': {
      id: '/autonomy'
      path: '/autonomy'
      fullPath: '/autonomy'
      preLoaderRoute: typeof AutonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/pipelines/$runId': {
      id: '/pipelines/$runId'
      path: '/$runId'
      fullPath: '/pipelines/$runId'
      preLoaderRoute: typeof PipelinesRunIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/knowledge/$pageId': {
      id: '/knowledge/$pageId'
      path: '/$pageId'
      fullPath: '/knowledge/$pageId'
      preLoaderRoute: typeof KnowledgePageIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/design/$designId': {
      id: '/design/$designId'
      path: '/$designId'
      fullPath: '/design/$designId'
      preLoaderRoute: typeof DesignDesignIdRouteImport
      parentRoute: typeof DesignRoute
    }
    '/conversations/$conversationId': {
      id: '/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof ConversationsConversationIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ConversationsRouteChildren {
  ConversationsConversationIdRoute: typeof ConversationsConversationIdRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsConversationIdRoute: ConversationsConversationIdRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

interface DesignRouteChildren {
  DesignDesignIdRoute: typeof DesignDesignIdRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignDesignIdRoute: DesignDesignIdRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgePageIdRoute: typeof KnowledgePageIdRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgePageIdRoute: KnowledgePageIdRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface PipelinesRouteChildren {
  PipelinesRunIdRoute: typeof PipelinesRunIdRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesRunIdRoute: PipelinesRunIdRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunsRoute: AgentRunsRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApiKeysRoute: ApiKeysRoute,
  AuditRoute: AuditRoute,
  AutonomyRoute: AutonomyRoute,
  BackupRoute: BackupRoute,
  BoardRoute: BoardRoute,
  CommunicationRoute: CommunicationRoute,
  ConnectionsRoute: ConnectionsRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  DesignRoute: DesignRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  DocumentsSettingsRoute: DocumentsSettingsRoute,
  ExtensionsRoute: ExtensionsRoute,
  ForgeRoute: ForgeRoute,
  HandsRoute: HandsRoute,
  IngressRoute: IngressRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  McpSettingsRoute: McpSettingsRoute,
  MeetingsRoute: MeetingsRoute,
  MemoryRoute: MemoryRoute,
  MissionControlRoute: MissionControlRoute,
  NodesRoute: NodesRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  ObservabilityRoute: ObservabilityRoute,
  OpsRoute: OpsRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProactiveRoute: ProactiveRoute,
  ProjectsRoute: ProjectsRoute,
  PromptSettingsRoute: PromptSettingsRoute,
  PromptsRoute: PromptsRoute,
  ProvidersRoute: ProvidersRoute,
  ResearchRoute: ResearchRoute,
  SchedulerRoute: SchedulerRoute,
  SearchResultsRoute: SearchResultsRoute,
  SearchSourcesRoute: SearchSourcesRoute,
  SecretsRoute: SecretsRoute,
  SecurityRoute: SecurityRoute,
  SelfLearningRoute: SelfLearningRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SkillEvolutionRoute: SkillEvolutionRoute,
  SkillsRoute: SkillsRoute,
  ToolsRoute: ToolsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
