// Part of eYssen. See LICENSE file for full copyright and licensing details.

/**
 * Client Wiki (Phase 4E stub) — Devin DeepWiki-inspired per-client living knowledge base.
 *
 * Initial version:
 *   - Left sidebar: tree of pages (grouped by parentId) + search box
 *   - Main area: markdown viewer (plain-text fallback pending Streamdown wiring) with Edit button
 *   - Edit mode: textarea + Save
 *   - Breadcrumb at top
 *
 * NOTE: Server-rendered HTML is available via ?render=html and is sanitized by
 * src/modules/client-wiki/markdown-render.ts. Until a sanitized renderer/component
 * is wired up on the frontend (see Streamdown in package.json), we show the
 * markdown body verbatim in a monospace block. This keeps the stub XSS-safe
 * without pulling DOMPurify into the bundle.
 */

import { useCallback, useEffect, useMemo, useState } from 'react'
import { api } from '@/lib/api'
import { t } from './i18n'

interface ClientWikiPage {
  id: string
  clientId: string
  slug: string
  title: string
  contentMd: string
  summary: string | null
  tags: string[]
  parentId: string | null
  createdAt: number
  updatedAt: number
  updatedBy: string | null
  autoGenerated: boolean
}

interface TreeNode {
  page: ClientWikiPage
  children: TreeNode[]
}

function buildTree(pages: ClientWikiPage[]): TreeNode[] {
  const byParent = new Map<string | null, ClientWikiPage[]>()
  for (const p of pages) {
    const key = p.parentId ?? null
    if (!byParent.has(key)) byParent.set(key, [])
    byParent.get(key)!.push(p)
  }
  const build = (parentId: string | null): TreeNode[] =>
    (byParent.get(parentId) ?? [])
      .slice()
      .sort((a, b) => a.title.localeCompare(b.title))
      .map(page => ({ page, children: build(page.id) }))
  return build(null)
}

function TreeItem({
  node, depth, selectedSlug, onSelect,
}: {
  node: TreeNode
  depth: number
  selectedSlug: string | null
  onSelect: (slug: string) => void
}) {
  const isSelected = node.page.slug === selectedSlug
  return (
    <div>
      <button
        type="button"
        onClick={() => onSelect(node.page.slug)}
        className={`w-full text-left px-2 py-1 rounded text-sm truncate ${
          isSelected ? 'bg-accent text-accent-foreground' : 'hover:bg-muted'
        }`}
        style={{ paddingLeft: 8 + depth * 12 }}
        title={node.page.title}
      >
        {node.page.autoGenerated ? '🤖 ' : ''}{node.page.title}
      </button>
      {node.children.length > 0 && (
        <div>
          {node.children.map(c => (
            <TreeItem key={c.page.id} node={c} depth={depth + 1} selectedSlug={selectedSlug} onSelect={onSelect} />
          ))}
        </div>
      )}
    </div>
  )
}

export default function ClientWikiPageView({ clientId }: { clientId: string }) {
  const [pages, setPages] = useState<ClientWikiPage[]>([])
  const [selectedSlug, setSelectedSlug] = useState<string | null>(null)
  const [current, setCurrent] = useState<ClientWikiPage | null>(null)
  const [query, setQuery] = useState('')
  const [searchResults, setSearchResults] = useState<ClientWikiPage[] | null>(null)
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchPages = useCallback(async () => {
    try {
      const ps = await api.get<ClientWikiPage[]>(`/client-wiki/${encodeURIComponent(clientId)}/pages`)
      setPages(ps)
      if (!selectedSlug && ps.length > 0) setSelectedSlug(ps[0].slug)
    } catch (e) {
      setError((e as Error).message)
    }
  }, [clientId, selectedSlug])

  const fetchCurrent = useCallback(async () => {
    if (!selectedSlug) { setCurrent(null); return }
    try {
      const page = await api.get<ClientWikiPage>(
        `/client-wiki/${encodeURIComponent(clientId)}/pages/${encodeURIComponent(selectedSlug)}`,
      )
      setCurrent(page)
      setDraft(page.contentMd)
    } catch (e) {
      setError((e as Error).message)
    }
  }, [clientId, selectedSlug])

  useEffect(() => { fetchPages() }, [fetchPages])
  useEffect(() => { fetchCurrent() }, [fetchCurrent])

  useEffect(() => {
    if (!query.trim()) { setSearchResults(null); return }
    const id = setTimeout(async () => {
      try {
        const hits = await api.get<ClientWikiPage[]>(
          `/client-wiki/${encodeURIComponent(clientId)}/search?q=${encodeURIComponent(query)}`,
        )
        setSearchResults(hits)
      } catch (e) {
        setError((e as Error).message)
      }
    }, 250)
    return () => clearTimeout(id)
  }, [query, clientId])

  const tree = useMemo(() => buildTree(pages), [pages])

  const handleSave = async () => {
    if (!current) return
    setSaving(true)
    setError(null)
    try {
      await api.put<ClientWikiPage>(
        `/client-wiki/${encodeURIComponent(clientId)}/pages/${encodeURIComponent(current.slug)}`,
        { contentMd: draft, changeSummary: 'Edited from UI' },
      )
      setEditing(false)
      await fetchCurrent()
    } catch (e) {
      setError((e as Error).message)
    } finally {
      setSaving(false)
    }
  }

  const breadcrumb = useMemo(() => {
    if (!current) return []
    const crumbs: ClientWikiPage[] = [current]
    let p: ClientWikiPage | undefined = current
    while (p?.parentId) {
      const parent = pages.find(x => x.id === p!.parentId)
      if (!parent) break
      crumbs.unshift(parent)
      p = parent
    }
    return crumbs
  }, [current, pages])

  return (
    <div className="flex h-full">
      <aside className="w-72 border-r flex flex-col">
        <div className="p-3 border-b">
          <input
            type="search"
            value={query}
            onChange={e => setQuery(e.target.value)}
            placeholder={t('clientWiki.searchPlaceholder')}
            className="w-full px-2 py-1 text-sm rounded border bg-background"
          />
        </div>
        <div className="flex-1 overflow-auto p-2">
          {searchResults ? (
            <div className="space-y-1">
              <div className="text-xs text-muted-foreground px-2 py-1">
                {t('clientWiki.searchResults')} ({searchResults.length})
              </div>
              {searchResults.map(p => (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => { setSelectedSlug(p.slug); setQuery('') }}
                  className="w-full text-left px-2 py-1 rounded text-sm hover:bg-muted"
                >
                  {p.title}
                </button>
              ))}
            </div>
          ) : (
            tree.map(node => (
              <TreeItem
                key={node.page.id}
                node={node}
                depth={0}
                selectedSlug={selectedSlug}
                onSelect={setSelectedSlug}
              />
            ))
          )}
          {!searchResults && pages.length === 0 && (
            <div className="text-sm text-muted-foreground p-2">{t('clientWiki.empty')}</div>
          )}
        </div>
      </aside>

      <main className="flex-1 overflow-auto">
        {error && (
          <div className="bg-destructive/15 text-destructive p-3 text-sm">{error}</div>
        )}
        {current ? (
          <div className="max-w-3xl mx-auto p-6">
            <nav className="text-xs text-muted-foreground mb-2">
              {breadcrumb.map((p, i) => (
                <span key={p.id}>
                  {i > 0 && ' / '}
                  {p.title}
                </span>
              ))}
            </nav>
            <div className="flex items-center justify-between mb-4">
              <h1 className="text-2xl font-semibold">{current.title}</h1>
              {!editing ? (
                <button
                  type="button"
                  onClick={() => setEditing(true)}
                  className="px-3 py-1 text-sm rounded border hover:bg-muted"
                >
                  {t('clientWiki.edit')}
                </button>
              ) : (
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => { setEditing(false); setDraft(current.contentMd) }}
                    className="px-3 py-1 text-sm rounded border hover:bg-muted"
                    disabled={saving}
                  >
                    {t('clientWiki.cancel')}
                  </button>
                  <button
                    type="button"
                    onClick={handleSave}
                    className="px-3 py-1 text-sm rounded bg-primary text-primary-foreground disabled:opacity-50"
                    disabled={saving}
                  >
                    {saving ? t('clientWiki.saving') : t('clientWiki.save')}
                  </button>
                </div>
              )}
            </div>
            {current.summary && !editing && (
              <p className="text-sm text-muted-foreground mb-4 italic">{current.summary}</p>
            )}
            {editing ? (
              <textarea
                value={draft}
                onChange={e => setDraft(e.target.value)}
                className="w-full h-[70vh] p-3 font-mono text-sm rounded border bg-background"
                spellCheck={false}
              />
            ) : (
              <pre className="whitespace-pre-wrap text-sm font-mono p-3 rounded border bg-muted/30">
                {current.contentMd}
              </pre>
            )}
            {current.tags.length > 0 && !editing && (
              <div className="mt-4 flex flex-wrap gap-1">
                {current.tags.map(tag => (
                  <span key={tag} className="px-2 py-0.5 text-xs rounded bg-muted">#{tag}</span>
                ))}
              </div>
            )}
          </div>
        ) : (
          <div className="h-full flex items-center justify-center text-muted-foreground">
            {t('clientWiki.selectPage')}
          </div>
        )}
      </main>
    </div>
  )
}
