{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eyas.inlineSecretName" . }}
  namespace: {{ include "eyas.namespace" . }}
  labels:
    {{- include "eyas.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
{{- range .Values.externalSecrets.items }}
{{- if $.Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "eyas.namespace" $ }}
  labels:
    {{- include "eyas.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .remoteRefs }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
{{- end }}
